title: Gowrisubha K
logo: https://cdn.pixabay.com/photo/2023/02/18/11/00/icon-7797704_640.png
description: This is a basic portfolio
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
